
version: '2'

services:
  environment-operator-jenkins-plugin:
     build: .
     container_name: "environment-operator-jenkins-plugin"
     hostname: "environment-operator-jenkins-plugin"
     volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./travis/script:/script
        - ./travis/jenkins:/var/jenkins_home
     environment:
        - JAVA_OPTS="-Djava.awt.headless=true"
     ports:
        - "0.0.0.0:50000:50000"
        - "0.0.0.0:8080:8080"